; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9F7719E5-58F8-497C-983C-16B38F831208}
AppName=QDaq
AppVersion=0.3.6
;AppVerName=QDaq 0.3.6
AppPublisher=QDaq contributors
AppPublisherURL=https://gitlab.com/qdaq/qdaq
AppSupportURL=https://gitlab.com/qdaq/qdaq
AppUpdatesURL=https://gitlab.com/qdaq/qdaq
ArchitecturesAllowed=x86compatible and not x64compatible
DefaultDirName={autopf}\QDaq
UninstallDisplayIcon={app}\qdaq.exe
DisableProgramGroupPage=yes
LicenseFile=Y:\Dev\qdaq\qdaq\LICENSE
InfoBeforeFile=Y:\Dev\qdaq\qdaq\README.md
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=Y:\Dev\qdaq\qdaq\.win32build\inno
OutputBaseFilename=qdaq-win32-0.3.6
SetupIconFile=Y:\Dev\qdaq\qdaq\tools\qdaq\qdaq_logo.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "Y:\Dev\qdaq\qdaq\.win32build\QDaq\qdaq.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Y:\Dev\qdaq\qdaq\.win32build\QDaq\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\QDaq"; Filename: "{app}\qdaq.exe"
Name: "{autodesktop}\QDaq"; Filename: "{app}\qdaq.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\qdaq.exe"; Description: "{cm:LaunchProgram,QDaq}"; Flags: nowait postinstall skipifsilent

