#ifndef INTERPOLATOR_GLOBAL_H
#define INTERPOLATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERPOLATOR_LIBRARY)
#  define INTERPOLATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INTERPOLATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERPOLATOR_GLOBAL_H
