#ifndef LINUXGPIB_GLOBAL_H
#define LINUXGPIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LINUXGPIB_LIBRARY)
#  define LINUXGPIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LINUXGPIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LINUXGPIB_GLOBAL_H
